---
- name: OmniSwitch Test
  hosts: all
  gather_facts: false

  tasks:
    - name: Show System
      raw: "show system"
      register: result

    - name: Display Output
      debug:
        var: result.stdout
`
